[package]
name = "conceptual-chain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[features]
day_001 = []
day_002 = []
day_003 = []
day_0003 = []